name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
        prefer_lowest: ["", "--prefer-lowest"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: $(composer config cache-files-dir)
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction ${{ matrix.prefer_lowest }} > /dev/null

      - name: Static analysis
        run: |
          composer check-deps
          PHP_CS_FIXER_IGNORE_ENV=1 composer cs-check
          composer phpstan -- --no-progress

      - name: Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --stop-on-failure || true
          composer run --timeout=0 infection || true

      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage.xml"
          comment: false
          comment_context: Coverage PHP ${{ matrix.php }} ${{ matrix.prefer-lowest }}
          status_context: Coverage PHP ${{ matrix.php }} ${{ matrix.prefer-lowest }}
          threshold_alert: 100
          threshold_warning: 100
